import sqlite3

connection = sqlite3.connect('database.db')
cursor = connection.cursor()

cursor.executescript('''
CREATE TABLE IF NOT EXISTS COURT_PARK (
    C_ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Address TEXT NOT NULL,
    Open_Time TEXT,
    Latitude REAL,
    Longitude REAL
);


CREATE TABLE IF NOT EXISTS INDIVIDUAL_COURTS (
    COURT_NUM INTEGER,
    C_ID INTEGER,
    PRIMARY KEY (COURT_NUM, C_ID),
    FOREIGN KEY (C_ID) REFERENCES COURT_PARK(C_ID)
);

CREATE TABLE IF NOT EXISTS TOURNAMENT (
    T_ID INTEGER PRIMARY KEY,
    Date TEXT NOT NULL,
    Type TEXT,
    Prize INTEGER,
    C_ID INTEGER,
    Status TEXT DEFAULT 'active',
    FOREIGN KEY (C_ID) REFERENCES COURT_PARK(C_ID)
);



CREATE TABLE IF NOT EXISTS PLAYER (
    P_ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Age INTEGER,
    Gender TEXT,
    T_ID INTEGER,
    FOREIGN KEY (T_ID) REFERENCES TOURNAMENT(T_ID)
);

CREATE TABLE IF NOT EXISTS GAME (
    G_ID INTEGER PRIMARY KEY,
    Result INTEGER,
    Time TEXT,
    Round INTEGER,
    T_ID INTEGER,
    FOREIGN KEY (T_ID) REFERENCES TOURNAMENT(T_ID)
);

CREATE TABLE IF NOT EXISTS PLAYER_GAME (
    P_ID INTEGER,
    G_ID INTEGER,
    T_ID INTEGER,
    FOREIGN KEY (P_ID) REFERENCES PLAYER(P_ID),
    FOREIGN KEY (G_ID) REFERENCES GAME(G_ID),
    FOREIGN KEY (T_ID) REFERENCES TOURNAMENT(T_ID),
    PRIMARY KEY (P_ID, G_ID, T_ID)
);


CREATE TABLE GAME_COURT (
    T_ID INTEGER,
    G_ID INTEGER,
    COURT_NUM INTEGER,
    C_ID INTEGER,
    PRIMARY KEY (T_ID, G_ID, COURT_NUM, C_ID),
    FOREIGN KEY (T_ID) REFERENCES TOURNAMENT(T_ID),
    FOREIGN KEY (G_ID) REFERENCES GAME(G_ID),
    FOREIGN KEY (COURT_NUM, C_ID) REFERENCES INDIVIDUAL_COURTS(COURT_NUM, C_ID)
);


''')

connection.commit()
connection.close()
